### ISSUE TITLE
Upload project to PYPI

### ISSUE THREAD

**Issue by omidekz** [mrvafa/aparat-downloader#1]
### i think that you can handle step  `<0, 1, 5, 6, 7>` by upload project to pypi. and for `<2, 3, 4>` use env vars, i mean search for selenium home and if user have not, raise error or guide to installation

**Comment by mrvafa** [comment]
Thanks for your feedback.
About the idea to upload the project to  PyPi, yeah why not! But unfortunately, the project is unstable I rather use PyPi in stable mode.
About the second idea, I rather stick with the traditional way. You know old habits.

**Comment by omidekz** [comment]
Benevolent dictator for life <3
