### ISSUE TITLE
Fails to extract links

### ISSUE THREAD

**Issue by el-lsan** [mrvafa/aparat-downloader#2]
I tried you example for hellodigi channel, however when I tried another channel like "dr.ahmadinejad" channel it fails.
I tried couple of times and it never succeed 

![image](https://user-images.githubusercontent.com/1249548/98165461-3c6cb280-1ee6-11eb-9cb4-c5c661bf166f.png)

![image](https://user-images.githubusercontent.com/1249548/98165545-602ff880-1ee6-11eb-9961-13391de05f07.png)

**Comment by mrvafa** [comment]
Thanks for your feedback.
I think your internet connection failed or interrupted. I run code for the "dr.ahmadinejad" channel and didn't get any errors. So I attached "links.json".
I will handle connection errors in future commits.
[links.zip](https://github.com/mrvafa/aparat-downloader/files/5492178/links.zip)

**Comment by el-lsan** [comment]
Not sure what might have gone wrong but my connection is pretty stable.
As I mentioned I had no issue while testing "hellodigi" channel however when I tried with "dr.ahmadinejad" channel if was failing no matter how many times I tried.
Could it be because of my env ?
FYI i'm using:
```
Geckodriver 0.28.0
Firefox 82.0.2
Python 3.9
Windows 10
```

Anyway thanks for attaching the links.
Looking forward to your updates on this repo.

Cheers

**Comment by mrvafa** [comment]
There wasn't any error on the windows. According to the last two lines of the error log, you send, "TimeoutError" I say it is internet interrupt or low speed. In this case, a channel with a small number of videos, like "hellodigi", run without any errors. while the "dr.ahmadinejad" channel has many videos you may get a timeout error.
